[project]
name = "12-pagination"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.10.1",
    "pydantic>=2.11.7",
    "starlette>=0.47.1",
]
